//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public User()
        {
            this.Appointments = new HashSet<Appointment>();
        }

        [Required(ErrorMessage = "Username is required!")]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "The username doesn't meet the required length complexity!")]
        public string Username { get; set; }


        [Required(ErrorMessage = "Password is required!")]
        [StringLength(50, ErrorMessage = "The password must be atleast {2} characters long!", MinimumLength = 8)]
        [DataType(DataType.Password)]
        public string Password { get; set; }


        [Required(ErrorMessage = "Name is required!")]
        [StringLength(50,ErrorMessage = "Name must be atleast {2} characters long!", MinimumLength = 2)]
        public string Name { get; set; }

        public short Role { get; set; }

        [DataType(DataType.EmailAddress, ErrorMessage = "Please enter a valid email!")]
        [EmailAddress(ErrorMessage = "Please enter a valid email!")]
        [RegularExpression("[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", ErrorMessage = "Invalid Email address")]
        public string Email { get; set; }

        public string Office { get; set; }
        public string Speciality { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
