//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Appointment
    {

        public int Id { get; set; }
        [Required(ErrorMessage = "Patient ID is required!")]
        public int Patient_Id { get; set; }
        [Required(ErrorMessage = "Please provide a Doctor ID")]
        public string Doctor_Id { get; set; }
        [DataType(DataType.Date, ErrorMessage = "Please enter a valid date!")]
        [Required(ErrorMessage = "Admission Date is required!")]
        public System.DateTime Admission_date { get; set; }
        [DataType(DataType.Date, ErrorMessage = "Please enter a valid date!")]
        public Nullable<System.DateTime> Discharge_date { get; set; }
        
        public virtual Patient Patient { get; set; }
        public virtual User User { get; set; }
    }
}
