//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        public Patient()
        {
            this.Appointments = new HashSet<Appointment>();
        }
        
        public int Id { get; set; }
        [Required(ErrorMessage = "Patient's name cannot be empty!")]
        public string Name { get; set; }

        [DataType(DataType.Date,ErrorMessage = "Please enter a valid date!")]
        public System.DateTime Birthdate { get; set; }

        [DataType(DataType.PhoneNumber,ErrorMessage ="That's not a valid phone number! Please enter a valid number.")]
        [StringLength(10, ErrorMessage = "The Phonenumber must be {2} characters!", MinimumLength = 10)]
        [RegularExpression("(\\d{10})", ErrorMessage ="Invalid Phone number")]
        public string Phone { get; set; }

        public string Address { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
